version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver:2.24.2
    container_name: geoserver
    restart: always
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver-data:/opt/geoserver/data_dir
